/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateEpicArgs } from "./CreateEpicArgs";
import { UpdateEpicArgs } from "./UpdateEpicArgs";
import { DeleteEpicArgs } from "./DeleteEpicArgs";
import { EpicCountArgs } from "./EpicCountArgs";
import { EpicFindManyArgs } from "./EpicFindManyArgs";
import { EpicFindUniqueArgs } from "./EpicFindUniqueArgs";
import { Epic } from "./Epic";
import { DevProject } from "../../devProject/base/DevProject";
import { EpicService } from "../epic.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Epic)
export class EpicResolverBase {
  constructor(
    protected readonly service: EpicService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Epic",
    action: "read",
    possession: "any",
  })
  async _epicsMeta(
    @graphql.Args() args: EpicCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Epic])
  @nestAccessControl.UseRoles({
    resource: "Epic",
    action: "read",
    possession: "any",
  })
  async epics(@graphql.Args() args: EpicFindManyArgs): Promise<Epic[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Epic, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Epic",
    action: "read",
    possession: "own",
  })
  async epic(@graphql.Args() args: EpicFindUniqueArgs): Promise<Epic | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Epic)
  @nestAccessControl.UseRoles({
    resource: "Epic",
    action: "create",
    possession: "any",
  })
  async createEpic(@graphql.Args() args: CreateEpicArgs): Promise<Epic> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Epic)
  @nestAccessControl.UseRoles({
    resource: "Epic",
    action: "update",
    possession: "any",
  })
  async updateEpic(@graphql.Args() args: UpdateEpicArgs): Promise<Epic | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Epic)
  @nestAccessControl.UseRoles({
    resource: "Epic",
    action: "delete",
    possession: "any",
  })
  async deleteEpic(@graphql.Args() args: DeleteEpicArgs): Promise<Epic | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DevProject, {
    nullable: true,
    name: "project",
  })
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "read",
    possession: "any",
  })
  async resolveFieldProject(
    @graphql.Parent() parent: Epic
  ): Promise<DevProject | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
