/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DevProjectService } from "../devProject.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DevProjectCreateInput } from "./DevProjectCreateInput";
import { DevProjectWhereInput } from "./DevProjectWhereInput";
import { DevProjectWhereUniqueInput } from "./DevProjectWhereUniqueInput";
import { DevProjectFindManyArgs } from "./DevProjectFindManyArgs";
import { DevProjectUpdateInput } from "./DevProjectUpdateInput";
import { DevProject } from "./DevProject";
import { EpicFindManyArgs } from "../../epic/base/EpicFindManyArgs";
import { Epic } from "../../epic/base/Epic";
import { EpicWhereUniqueInput } from "../../epic/base/EpicWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DevProjectControllerBase {
  constructor(
    protected readonly service: DevProjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DevProject })
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DevProjectCreateInput,
  })
  async create(
    @common.Body() data: DevProjectCreateInput
  ): Promise<DevProject> {
    return await this.service.create({
      data: {
        ...data,

        owner: {
          connect: data.owner,
        },
      },
      select: {
        createdAt: true,
        description: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DevProject] })
  @ApiNestedQuery(DevProjectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<DevProject[]> {
    const args = plainToClass(DevProjectFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DevProject })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: DevProjectWhereUniqueInput
  ): Promise<DevProject | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DevProject })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DevProjectUpdateInput,
  })
  async update(
    @common.Param() params: DevProjectWhereUniqueInput,
    @common.Body() data: DevProjectUpdateInput
  ): Promise<DevProject | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          owner: {
            connect: data.owner,
          },
        },
        select: {
          createdAt: true,
          description: true,
          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DevProject })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: DevProjectWhereUniqueInput
  ): Promise<DevProject | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/epics")
  @ApiNestedQuery(EpicFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Epic",
    action: "read",
    possession: "any",
  })
  async findManyEpics(
    @common.Req() request: Request,
    @common.Param() params: DevProjectWhereUniqueInput
  ): Promise<Epic[]> {
    const query = plainToClass(EpicFindManyArgs, request.query);
    const results = await this.service.findEpics(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        project: {
          select: {
            id: true,
          },
        },

        tite: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/epics")
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "update",
    possession: "any",
  })
  async connectEpics(
    @common.Param() params: DevProjectWhereUniqueInput,
    @common.Body() body: EpicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      epics: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/epics")
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "update",
    possession: "any",
  })
  async updateEpics(
    @common.Param() params: DevProjectWhereUniqueInput,
    @common.Body() body: EpicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      epics: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/epics")
  @nestAccessControl.UseRoles({
    resource: "DevProject",
    action: "update",
    possession: "any",
  })
  async disconnectEpics(
    @common.Param() params: DevProjectWhereUniqueInput,
    @common.Body() body: EpicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      epics: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
